version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  crawler:
    image: crawler
    container_name: crawler
    links:
      - postgres
    depends_on:
      - postgres

  streamlit:
    image: streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    links:
      - postgres
    depends_on:
      - crawler